### ISSUE TITLE
Not working Magento 1.9?

### ISSUE THREAD

**Issue by globello** [RobM84/Magento-Robm-Tracking#2]
I performed the installation, but it does not work, does not create the database tables.
Is there a trick for installation?

**Comment by RobM84** [comment]
Hi,

I never tested with 1.9.
It is not supposed to create a database table. It adds a column to sales_flat_order and creates a new customer attribute which is saved in the EAV-structure.
See here:

- https://github.com/RobM84/Magento-Robm-Tracking/blob/master/app/code/community/Robm/Tracking/sql/robm_tracking_setup/mysql4-install-0.0.1.php
- https://github.com/RobM84/Magento-Robm-Tracking/blob/master/app/code/community/Robm/Tracking/sql/robm_tracking_setup/mysql4-upgrade-0.0.1-0.0.2.php


Best
